### ISSUE TITLE
Option to stop on last image

### ISSUE THREAD

**Issue by nacalai** [dustymethod/BrowserImageSlideshow#1]
Hi there! I just found this plugin, and modified it so it sorts the files by date modified, but that's where my skills stop. You could add an option in settings.js to stop on last image? I want to implement this on our financial news shows and automate a lot of stuff and would love to take this plugin into use, but I need the last slide to stay while we fade out music, and not fade to the beginning again.

Thanks!

**Comment by dustymethod** [comment]
Hi there,

I've added your requested feature. Unfortunately I don't have the time to test it extensively, but so far it seems to work as intended. To enable your slideshow to stop on the last image, set stopOnLastImage in settings.js to true.

(make sure to re-download the code from the master branch, and update your source in OBS. you will probably need to integrate your modifications again.)
