### ISSUE TITLE
Gifs lag and stutter/restart when transitioning between them

### ISSUE THREAD

**Issue by Shadowthecat35** [dustymethod/BrowserImageSlideshow#3]
I use this script a lot since it's the best alternative right now for a slideshow without the size limit so if you ever come back to update the project, adding a fix for gifs as well as some options for a slide in transition would be appreciated!

**Comment by dustymethod** [comment]
Thanks for letting me know, I'll try to fix it when I have the time. It looks like it has to do with the way I did the fade transition. Works ok for images, not so well for gifs :s

Looks like I may have to redo the transitions, so I'll see if I can include more options

**Comment by dustymethod** [comment]
I think I've fixed the issue, feel free to give the new version a try:

[v1.4](https://github.com/dustymethod/BrowserImageSlideshow/releases/tag/v1.4)

No new transition options unfortunately, but maybe in the future.

**Comment by Shadowthecat35** [comment]
> I think I've fixed the issue, feel free to give the new version a try:
> 
> [v1.4](https://github.com/dustymethod/BrowserImageSlideshow/releases/tag/v1.4)
> 
> No new transition options unfortunately, but maybe in the future.

Just logged on to check your response. You are awesome, thanks a ton for looking into it!! I'll update when I get home tonight!
