### ISSUE TITLE
Change how the browser slideshow skips files

### ISSUE THREAD

**Issue by SocksTheWolf** [dustymethod/BrowserImageSlideshow#6]
Currently there's a short list of file extensions that are ignored if they exist in the current directory. The problem is that there could always be other files in the directory as well that are not images, but this script will attempt to render them as images, causing undefined behavior.

To get around this, I wanted to suggest changing the ignore list to an allow list. I've went ahead and done so in #5, putting in the most common image extension formats that are supported by the OBS browser. With a change like this, users wouldn't have to go into the page code and keep adding file extensions to ignore.

The end result is that the file is more portable and scalable to various use cases.

**Comment by dustymethod** [comment]
Great idea, thanks! Your change has been added
